<?php
$word = str_split($this->word['word']);
$letterCount = count($word);
?>
 <div id="score_div">
    <button type="button" id="statistic" class="btn btn-default">Statistic</button>
    <button type="button" id="exit" class="btn btn-default">Exit</button>
    </div>
<div class="jumbotron" style="text-align:center">
   
    <div class="" role="alert" id="alert_messsage"><span class="msg"></span></div>
    <input type="hidden" id="word_length" value="<?php echo $letterCount; ?>">
    <?php
    for ($i = 0; $i < $letterCount; $i++) {
        if ($i == 0 || $i == $letterCount-1) { ?>
        <input type="text" class="word_input input_text_bold" maxlength="1" 
            style='text-transform:uppercase' align="center" 
            value="<?php echo $word[$i] ?>" readonly>
        <?php } else { ?>
        <input type="text"  id="input_id_<?php echo $i;?>" class="word_input first_last_input" maxlength="1" 
            style='text-transform:uppercase' align="center" 
            value="" 
            oninput="return alphaOnly('<?php echo $word[$i]; ?>',<?php echo $i;?>);">
<!--        <img class= "wrong_sign" src="<?php echo $this->basePath() . '/img/cross.png' ?>" alt="wrong" height="10px;" width="10px">-->
    <?php } } ?>
        <button type="button" class="btn btn-default" data-toggle="tooltip"
                data-placement="top" title="<?php echo  $this->word['word_hint']; ?>">Hint</button>
        <button type="button" id="new_game" hidden="hidden" class="btn btn-default">New game</button>
</div>