<?php
$title = 'Add New Player';
$this->headTitle($title);
?>
<div id="register_div" class="center">
      <input type="hidden" id="word_length" value="">
    <input type="hidden" id="chartContainer" value="">
    <h1 class="register_text"><?= $this->escapeHtml($title) ?></h1>
    <hr>
    <?php
    $form->setAttribute('action', $this->url('user', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
//    echo $this->formRow($form->get('title'));
    echo $this->formRow($form->get('first_name'));
    echo $this->formRow($form->get('last_name'));
//    echo $this->formRow($form->get('email'));
    echo $this->formRow($form->get('username'));
    echo $this->formRow($form->get('password'));
    echo $this->formRow($form->get('cnfpassword'));
//    echo $this->formRow($form->get('address'));
    echo $this->formRow($form->get('phone'));
//    echo $this->formRow($form->get('state'));
//    echo $this->formRow($form->get('city'));
    echo $this->formRow($form->get('country'));
//    echo $this->formRow($form->get('aboutme'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
