<?php
$title = 'Login';
$this->headTitle($title);
?>
<div id="login_div" class="center">
    <h1 class="login_text"><?= $this->escapeHtml($title) ?></h1>
    <hr>
    <?php
    $form->setAttribute('action', $this->url('user', ['action' => 'login']));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('username'));
    echo $this->formRow($form->get('password'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
