<?php
print_r($this->loggedInUser);
?>
<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Hangman Game</span></h1>
    <?php if (empty($this->loggedInUser)) { ?>
        <p><a class="btn btn-success btn-lg center" href="<?= $this->url('user', ['action' => 'login']) ?>" target="_self">Login</a>

           <a class="btn btn-success btn-lg center" href="<?= $this->url('user', ['action' => 'add']) ?>" target="_self">Register</a></p>

    <?php } else { ?>
        <p><a class="btn btn-success btn-lg center" href="<?= $this->url('game', ['action' => 'newGame']) ?>" target="_self">New Game</a>

            <!--<a class="btn btn-success btn-lg center" href="<?php //$this->url('game', ['action' => 'resumeGame']) ?>" target="_self">Resume Game</a>-->
             <a class="btn btn-success btn-lg center" href="<?= $this->url('user', ['action' => 'logout']) ?>" target="_self">Exit</a></p>
        <?php } ?>
        
</div>
